### ISSUE TITLE
"mvn package" fails

### ISSUE THREAD

**Issue by Ciribomflax** [CSCfi/shibboleth-idp-oidc-extension#38]
Error: Failed to execute goal on project idp-oidc-extension-impl: Could not resolve dependencies for project org.geant:idp-oidc-extension-impl:jar:1.1.1-SNAPSHOT: Failure to find com.duosecurity:DuoWeb:jar:1.3

**Comment by Ciribomflax** [comment]
solved by downloading https://build.shibboleth.net/nexus/content/groups/public/com/duosecurity/DuoWeb/1.3/DuoWeb-1.3.jar to local maven repo, but this is not a good solution

**Comment by hjmikkon** [comment]
I haven't been able to reproduce this. Is the same issue still existing for you? Have you tried the compilation in any other machines?
